synonym = { 'maryjane': {'mary jane'},          
            'motherfuck': {'mutha fuck', 'mutherfuck', 'mother fuck'},
            'motherfucker': {'motha fucka', 'motherfucka', 'muther fucka' }, 
            'motherfucking': {'mothafuckin', 'motha fuckin', 'mothafucking', 'motha fucking', 'muthafuckin', 'mutha fuckin', 'muthafucking', 'mutha fucking'},
            'everybody ': {'everybodys'}, 
            'smokin': {'smoking'},
            'sniffin': {'sniffing'},
            'nigga' : {'niggas', 'niggaz'},  
            'what the fuck' : {'wtf'},
            'baby' : {'babe', 'babies', 'bae'},   
            'cowboy' : {'cowboys', 'cow boy', 'cow boys'}, 
            ' because ' : {' cuz ', ' coz ', ' cus ', ' bc ', ' cause ', '\'cause'},             
            'crackhead': {'crack head', 'crackheads', 'crack heads', 'cracked head', 'cracked heads'},
            'jordan': {'jordan', 'jordans'},
            'bitch': {'bitches'},
            'bitchin' : {'bitching'}, 
            'i ' : {'imma ', 'ive ', 'i\'m', 'i\'ve', 'i\'d', 'I\'m', 'im '},
            ' i ' : {' id ', ' ive ', ' im '},
            'try': {'tryna'},
            'heroin' : {'heroine', 'heroines', 'heroins'}, 
            'hoe ' : {'hoes ', 'hoe ', 'hos ', 'ho '}, 
            'homie': {'homies', 'hommies'}, 
            'crystal' : {'crystals', 'cristal', 'cristals'}, 
            'fuck' : {'fuk', 'fk'},
            'fucked' : {'fuked', 'fked'},
            'fuckin' : {'fukin', 'fckin', 'fuking', 'fcking', 'fkin', 'fucking'},
            'fucker' : {'fucka', 'fckas', 'fuckers', 'fckers'}, 
            'gangsta' : {'gangstas','gangster', 'gangsters'},
            'faggot' : {'fag', 'faggots', 'fags'}, 
            'shawty' : {'shorty', 'shawnty'},
            'gonna' : {'gon\'', 'gone'}, 
            'about' : {'\'bout'}, 
            'ballin' : {'balling'}, 
            'bangin' : {'banging'}, 
            'bean' : {'beans'},
            'beam' : {'beams'},
            'between' : {'betwen'},
            ' before': {' fore', '\'fore'},

            'bleeding' : {'bleding'},
            'blunt' : {'blunts', 'blunted'}, 
            'bond' : {'bonds'}, 
            'bone' : {'bones'}, 
            'bong' : {'bongs'}, 
            'bottle' : {'bottles'}, 
            'box' : {'boxes'}, 
            'boy' : {'boyz', 'boys'}, 
            'breath' : {'breathe'}, 
            'buddha' : {'buddahs'}, 
            'buildin' : {'building'}, 
            'bumpin' : {'bumping'},
            'burn' : {'burned', 'burns', 'burnt'},
            'burner' : {'burners'}, 
            'burnin' : {'burning'}, 
            'bustin' : {'busting'}, 
            'ceilin' : {'ceiling'},
            'chokin' : {'choking'},
            'choppin' : {'chopping'}, 
            'cigarette' : {'cigarettes'},
            'clear' : {'clears'}, 
            'club' : {'clubs'}, 
            'clutchin' : {'clutching'}, 
            'comin' : {'coming'}, 
            'cook' : {'cooks', 'cooked'},
            'cookin' : {'cooking'}, 
            'cookie' : {'cookies'}, 
            'cop' : {'cops'}, 
            'corner' : {'corners'}, 
            'countin' : {'counting'}, 
            'creep' : {'crep'}, 
            'creeping' : {'creping'}, 

            'crushin' : {'crushing'}, 
            'dad' : {'daddy'}, 
            'dancin' : {'dancing'}, 
            'dawg' : {'dawgs'}, 
            'deal' : {'deals'}, 
            'dealer' : {'dealers'}, 
            'dealin' : {'dealing'}, 
            'designer' : {'desiigner'}, 
            'disappear' : {'disappears', 'disappeared'}, 
            'doc' : {'doctor', 'doctors'}, 
            'dog' : {'dogg', 'dogs'}, 
            'father' : {'fathers'}, 
            'fifth' : {'5th'}, 

            'gettin' : {'getting'},
            'goddamn' : {'god damn'},
            'grade' : {'gradeee'},
            
            'hatin' : {'hating'},
            'havin' : {'having'},
            
            'human': {'humans'}, 
            'hour' : {'hours'}, 
            'supposed' : {'s\'posed'},
            'sniffin' : {'sniffin\'', 'sniffing'},
            'yall' : {'y\'all'}
}

class Normalizer:

    def normalize(self, lyrics):
        for key in synonym: 
            for el in synonym[key]:
                lyrics = lyrics.lower()               
                if (lyrics.find(el)!=-1):
                    lyrics = lyrics.replace(el, key)
        return lyrics
    
